// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrailerPark.Infrastructure.Config;

#nullable disable

namespace TrailerPark.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105135046_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrailerPark.Core.Models.Country", b =>
                {
                    b.Property<string>("Alpha2")
                        .HasColumnType("text");

                    b.Property<string>("Alpha3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Alpha2");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TrailerPark.Core.Models.Movie", b =>
                {
                    b.Property<string>("imdbID")
                        .HasColumnType("text");

                    b.Property<List<string>>("Actors")
                        .HasColumnType("text[]");

                    b.Property<string>("Awards")
                        .HasColumnType("text");

                    b.Property<decimal?>("BoxOffice")
                        .HasColumnType("numeric");

                    b.Property<string>("CountryAlpha2")
                        .HasColumnType("text");

                    b.Property<string>("DVD")
                        .HasColumnType("text");

                    b.Property<List<string>>("Director")
                        .HasColumnType("text[]");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Metascore")
                        .HasColumnType("text");

                    b.Property<string>("Plot")
                        .HasColumnType("text");

                    b.Property<string>("Poster")
                        .HasColumnType("text");

                    b.Property<string>("Production")
                        .HasColumnType("text");

                    b.Property<string>("Rated")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Released")
                        .HasColumnType("date");

                    b.Property<int?>("RuntimeMin")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("TypeID")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.Property<List<string>>("Writer")
                        .HasColumnType("text[]");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.Property<string>("imdbRating")
                        .HasColumnType("text");

                    b.Property<int?>("imdbVotes")
                        .HasColumnType("integer");

                    b.HasKey("imdbID");

                    b.HasIndex("CountryAlpha2");

                    b.HasIndex("TypeID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("TrailerPark.Core.Models.Rating", b =>
                {
                    b.Property<int?>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("RatingID"));

                    b.Property<string>("MovieimdbID")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("RatingID");

                    b.HasIndex("MovieimdbID");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("TrailerPark.Core.Models.Type", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeID"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("TypeID");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("TrailerPark.Core.Models.Movie", b =>
                {
                    b.HasOne("TrailerPark.Core.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryAlpha2");

                    b.HasOne("TrailerPark.Core.Models.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID");

                    b.Navigation("Country");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("TrailerPark.Core.Models.Rating", b =>
                {
                    b.HasOne("TrailerPark.Core.Models.Movie", null)
                        .WithMany("Ratings")
                        .HasForeignKey("MovieimdbID");
                });

            modelBuilder.Entity("TrailerPark.Core.Models.Movie", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
