name: .NET Build CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.22"

      - name: Restore the solution
        run: dotnet restore TrailerPark.sln

      - name: Build the solution
        run: dotnet build TrailerPark.sln -c Release --no-restore
